apiVersion: addons.sigs.k8s.io/v1alpha1
kind: Nomos
metadata:
  name: nomos-acme
  namespace: nomos-system
spec:
  enableHierarchicalResourceQuota: true
  git:
    secretType: ssh
    syncRepo: git@github.com:sandyjensen/nomos-acme-corp.git
    syncBranch: master
    policyDir: nomos-root
