kind: NamespaceSelector
apiVersion: nomos.dev/v1alpha1
metadata:
  name: selector-envnonprod
spec:
  selector:
    matchExpressions:
      - {key: environment, operator: NotIn, values: [production]}


